import {
  PRIMARY_BLUE,
  SECONDARY_BLUE,
  GRAYISH_BLUE,
  LIGHT_BLUE,
  WHITE,
  GRAY_11,
  GRAY_11_OPACITY_50,
  GRAY_8,
  GRAY_7,
  GRAY_6,
  GRAY_6_95,
  GRAY_5,
  GRAY_4,
  GRAY_3,
  GRAY_2,
  GRAY_1,
  BLACK,
  SHADOW_DARK,
  SHADOW_LIGHT,
  CHART_BLUE,
  GRAY_1_OPACITY,
  RAIN_1,
  RAIN_2,
  RAIN_3,
  RAIN_4,
  RAIN_5,
  RAIN_6,
  RAIN_7,
  RAIN_8,
  TRANSPARENT,
  GRAY_9_OPACITY_10,
  GRAY_10_OPACITY_60,
  GRAY_4_OPACITY_50,
  MEDIUM_BLUE,
} from '@assets/colors';
import { Platform } from 'react-native';

const fonts = Platform.select({
  default: {
    regular: {
      fontFamily: 'Roboto-Regular',
      fontWeight: '400' as const,
    },
    medium: {
      fontFamily: 'Roboto-Medium',
      fontWeight: '500' as const,
    },
    bold: {
      fontFamily: 'Roboto-Bold',
      fontWeight: '600' as const,
    },
    heavy: {
      fontFamily: 'Roboto-Bold',
      fontWeight: '700' as const,
    },
  }
});

export const lightTheme = {
  dark: false,
  blue: false,
  colors: {
    primary: SECONDARY_BLUE,
    background: WHITE,
    card: WHITE,
    text: PRIMARY_BLUE,
    notification: WHITE,
    primaryText: BLACK,
    secondaryText: GRAY_3,
    border: GRAYISH_BLUE,
    inputBackground: GRAY_11,
    inputButtonBackground: WHITE,
    mapButtonBackground: WHITE,
    relocateButtonBackground: SECONDARY_BLUE,
    mapButtonBorder: GRAYISH_BLUE,
    headerBackground: WHITE,
    timeStepBackground: LIGHT_BLUE,
    shadow: SHADOW_LIGHT,
    screenBackground: LIGHT_BLUE,
    cardHeader: GRAY_9_OPACITY_10,
    cardShadow: GRAYISH_BLUE,
    warningsIconFill: PRIMARY_BLUE,
    selectedDayBackground: LIGHT_BLUE,
    chartPrimaryLine: PRIMARY_BLUE,
    chartSecondaryLine: SECONDARY_BLUE,
    chartGrid: GRAY_8,
    chartGridDay: GRAY_4,
    hourListText: GRAY_4,
    secondaryBorder: GRAY_1,
    tabBarInactive: PRIMARY_BLUE,
    tabBarActive: SECONDARY_BLUE,
    timeSliderObservationText: GRAY_3,
    timeSliderTick: GRAY_2,
    listTint: GRAY_1_OPACITY,
    rain: {
      0: TRANSPARENT,
      1: RAIN_1,
      2: RAIN_2,
      3: RAIN_3,
      4: RAIN_4,
      5: RAIN_5,
      6: RAIN_6,
      7: RAIN_7,
      8: RAIN_8,
    },
    accordionContentBackground: 'rgb(246,249,253)',
    modalBackground: WHITE,
    selectedButton: WHITE,
    warningCard: '#E8EFF5',
    warningCardBorder: MEDIUM_BLUE,
    weatherButtonBackground: GRAY_11_OPACITY_50,
    meteorologistSnapshotCard: '#f3f3f3',
    forecastBackground: MEDIUM_BLUE,
  },
  fonts
};

export const darkTheme = {
  dark: true,
  blue: false,
  colors: {
    primary: WHITE,
    background: BLACK,
    card: GRAY_7,
    text: WHITE,
    notification: WHITE,
    primaryText: WHITE,
    secondaryText: GRAY_1,
    border: GRAY_3,
    inputBackground: GRAY_4_OPACITY_50,
    inputButtonBackground: GRAY_5,
    mapButtonBackground: GRAY_6_95,
    relocateButtonBackground: GRAY_6,
    mapButtonBorder: GRAY_7,
    headerBackground: GRAY_6,
    timeStepBackground: GRAY_6,
    shadow: SHADOW_DARK,
    screenBackground: GRAY_7,
    cardHeader: GRAY_10_OPACITY_60,
    cardShadow: BLACK,
    warningsIconFill: BLACK,
    selectedDayBackground: GRAY_4,
    chartPrimaryLine: CHART_BLUE,
    chartSecondaryLine: GRAYISH_BLUE,
    chartGrid: GRAY_3,
    chartGridDay: WHITE,
    hourListText: WHITE,
    secondaryBorder: GRAY_1,
    tabBarInactive: GRAY_1,
    tabBarActive: WHITE,
    timeSliderObservationText: GRAY_1,
    timeSliderTick: GRAY_1,
    listTint: GRAY_1_OPACITY,
    rain: {
      0: TRANSPARENT,
      1: RAIN_1,
      2: RAIN_2,
      3: RAIN_3,
      4: RAIN_4,
      5: RAIN_5,
      6: RAIN_6,
      7: RAIN_7,
      8: RAIN_8,
    },
    accordionContentBackground: 'rgb(246,249,253)',
    modalBackground: 'rgb(25,25,25)',
    selectedButton: BLACK,
    warningCard: GRAY_6,
    warningCardBorder: GRAY_4,
    weatherButtonBackground: GRAY_4_OPACITY_50,
    meteorologistSnapshotCard: GRAY_6,
    forecastBackground: GRAY_2,
  },
  fonts,
};

export const blueTheme = {
  dark: true,
  blue: true,
  colors: {
    primary: WHITE,
    background: '#0F0F2D',
    card: GRAY_7,
    text: WHITE,
    notification: WHITE,
    primaryText: WHITE,
    secondaryText: GRAY_1,
    border: '#BDD7E9',
    inputBackground: GRAY_4_OPACITY_50,
    inputButtonBackground: GRAY_5,
    mapButtonBackground: GRAY_6_95,
    relocateButtonBackground: GRAY_6,
    mapButtonBorder: GRAY_7,
    headerBackground: GRAY_6,
    timeStepBackground: GRAY_6,
    shadow: SHADOW_DARK,
    screenBackground: GRAY_7,
    cardHeader: 'rgba(21, 24, 58, 0.4)',
    cardShadow: BLACK,
    warningsIconFill: BLACK,
    selectedDayBackground: GRAY_4,
    chartPrimaryLine: CHART_BLUE,
    chartSecondaryLine: GRAYISH_BLUE,
    chartGrid: GRAY_3,
    chartGridDay: WHITE,
    hourListText: WHITE,
    secondaryBorder: GRAY_1,
    tabBarInactive: WHITE,
    tabBarActive: '#00D7FF',
    timeSliderObservationText: GRAY_1,
    timeSliderTick: GRAY_1,
    listTint: GRAY_1_OPACITY,
    rain: {
      0: TRANSPARENT,
      1: RAIN_1,
      2: RAIN_2,
      3: RAIN_3,
      4: RAIN_4,
      5: RAIN_5,
      6: RAIN_6,
      7: RAIN_7,
      8: RAIN_8,
    },
    accordionContentBackground: 'rgb(246,249,253)',
    modalBackground: '#1F2060',
    selectedButton: '#1F2060',
    warningCard: 'rgba(76, 76, 103, 0.6)',
    warningCardBorder: 'rgb(147, 184, 209)',
    weatherButtonBackground: GRAY_4_OPACITY_50,
    meteorologistSnapshotCard: 'rgba(76, 76, 103, 0.6)',
  },
  fonts,
};
